language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  matrix:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=WTForms==2.1

install:
  - "pip install $WTFORMS"
  - pip install -e ".[test]"
script:
  - flake8 wtforms_json tests
  - python setup.py test
